
       <div id="contenido2">
        
            <div class="container-titulo">
                <h2>Términos y condiciones📝</h2>
            </div>
            <div class="container-central">
                <p>Bienvenido al sitio de internet: www.lenceriRM.com, (en adelante, el &quot;Sitio&quot;) de Medina S.A. Es voluntad de Medina S.A: dar a conocer los t&eacute;rminos y condiciones (en adelante los &quot;T&eacute;rminos y Condiciones&quot;), que se describir&aacute;n a continuaci&oacute;n, los cuales tienen por objeto regular el acceso y utilizaci&oacute;n de las personas que ingresen al Sitio. Se hace saber que el t&eacute;rmino &quot;Usuario&quot; del Sitio comprende a aquellos que se encuentran registrados y a los visitantes, (en adelante, el &quot;Usuario&quot;).</p>

                <p>Al registrarse y/o navegar en el presente Sitio, el Usuario presta su debido consentimiento a los presentes T&eacute;rminos y Condiciones.</p>

                <p>Tanto los T&eacute;rminos y Condiciones como las Pol&iacute;ticas de Privacidad y/o informaciones sobre el Sitio se considerar&aacute;n de aplicaci&oacute;n para todo Usuario del Sitio, implicando su respectiva aceptaci&oacute;n a contar desde el primer momento en que &eacute;ste acceda al Sitio.</p>

                <p>Los presentes t&eacute;rminos y condiciones tienen car&aacute;cter obligatorio y vinculante. Son aplicables a todas las compras y actividades realizadas en el presente Sitio. Si el Usuario no acepta en forma total los presentes T&eacute;rminos y Condiciones, y las Pol&iacute;ticas de Privacidad, le rogamos que no contin&uacute;e con el acceso y visita de nuestro Sitio. En el supuesto de avanzar con la visita en nuestro Sitio, se entender&aacute; que el Usuario acept&oacute; los presentes T&eacute;rminos y Condiciones, las Pol&iacute;ticas de Privacidad y acepta recibir e-mails peri&oacute;dicos con la informaci&oacute;n que el Sitio determine.</p>

                <p>Las violaciones a los presentes T&eacute;rminos y Condiciones generar&aacute;n un derecho a favor del titular del Sitio a suspender o finalizar la prestaci&oacute;n de su servicio al Usuario que las haya realizado, por acci&oacute;n u omisi&oacute;n. El Sitio se preocupa por la protecci&oacute;n de datos de car&aacute;cter personal de los Usuarios, intentando mantener la privacidad de la informaci&oacute;n que sea provista por el usuario de acuerdo a los lineamientos expuestos en nuestra Pol&iacute;tica de Privacidad.</p>

                <p>Los T&eacute;rminos y Condiciones y las Pol&iacute;ticas de Privacidad podr&aacute;n ser modificados en todo o en parte en cualquier momento y a exclusivo criterio de Medina S.A. Dichas reformas e implementaciones tendr&aacute;n vigencia a partir del momento mismo en que sean publicados o insertados en el Sitio o desde que sean notificados al Usuario por cualquier medio, lo que ocurra primero. Por lo expuesto, le sugerimos que los visite peri&oacute;dicamente.</p>

                <p>Los productos y servicios que se ofrecen por a trav&eacute;s del Sitio (en adelante, los &quot;Productos&quot;), s&oacute;lo se encuentran disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no obedezcan a esta condici&oacute;n deber&aacute;n abstenerse de suministrar informaci&oacute;n personal para ser incluida en nuestras bases de datos. No obstante pueden hacerlo a trav&eacute;s de sus padres o tutores. Los padres, tutores o responsables de los menores de edad o incapaces que utilicen el Sitio ser&aacute;n responsables por dicho uso, incluyendo cualquier cargo, facturaci&oacute;n o da&ntilde;o que se derive de &eacute;l. Si el Usuario est&aacute; registrado como Empresa, deber&aacute; tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los t&eacute;rminos del presente.&nbsp;</p>

                <h3><strong>Propiedad Intelectual</strong></h3>

                <p>El contenido del Sitio, junto con y sin que se considere una limitaci&oacute;n, sus logotipos, programas, bases de datos, im&aacute;genes, gr&aacute;ficos, dise&ntilde;os, software, programaci&oacute;n, textos informaci&oacute;n y archivos son de propiedad de Medina S.A. y se encuentra protegido por normas locales y tratados internacionales</p>

                <p>Su uso indebido as&iacute; como su reproducci&oacute;n, modificaci&oacute;n, exhibici&oacute;n, venta o distribuci&oacute;n del contenido sin el expreso y escrito consentimiento previo de Medina S.A. ser&aacute; objeto de las acciones judiciales que correspondan.</p>

                <p>El presente acuerdo no podr&aacute; ser interpretado como un contrato de sociedad, mandato o que genere ning&uacute;n tipo de relaci&oacute;n entre el Sitio y el Usuario. El uso de Internet y el Sitio implica la asunci&oacute;n de riesgos de da&ntilde;os al software y al hardware del usuario. Documentos y archivos pueden contener virus y, como es el caso de cualquier computadora interconectada, la computadora del Usuario puede ser atacada por hackers que podr&iacute;an tener acceso a la informaci&oacute;n contenida en la computadora del Usuario, extraerla o da&ntilde;arla. El env&iacute;o de informaci&oacute;n a trav&eacute;s de la red o a trav&eacute;s de e-mails tiene el riesgo de que tal informaci&oacute;n pueda ser captada por un tercero. El Sitio no se hace responsable de las consecuencias que pudiera acarrear al Usuario la asunci&oacute;n por parte del Usuario de ese riesgo. El Sitio no tiene obligaci&oacute;n alguna de conservar ninguna informaci&oacute;n que haya hecho disponible a los Usuarios ni que le haya sido enviada por los Usuarios. Las funciones contenidas en el Sitio y el acceso al mismo pueden ser interrumpidas en cualquier momento y contener errores.&nbsp;</p>

                <p>Excepto en aquellos casos en que la responsabilidad de Medina S.A. pueda estar limitada por medio de una Pol&iacute;tica Espec&iacute;fica, en todo otro caso de existir responsabilidad de Medina S.A. o de los Proveedores de productos e informaci&oacute;n de productos, ya sea en forma individual o conjunta, por cualquier tipo de da&ntilde;os vinculados al producto, el monto de la misma no exceder&aacute; en su totalidad la retribuci&oacute;n pagada por el Usuario por el uso del producto en cuesti&oacute;n o del producto provisto, seg&uacute;n sea el caso.&nbsp;</p>

                <p>Para adquirir los Productos ofrecidos por el Sitio, los Usuarios deber&aacute;n facilitar ciertos datos de car&aacute;cter personal. Su informaci&oacute;n personal ser&aacute; procesada y almacenada en servidores de Medina S.A. Para mayor informaci&oacute;n sobre la privacidad de los Datos Personales y casos en los que ser&aacute; revelada la informaci&oacute;n personal, se pueden consultar nuestras Pol&iacute;ticas de Privacidad.</p>

                <p>No se permitir&aacute; ninguna acci&oacute;n o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de Medina S.A. como en las ofertas, descripciones, cuentas o bases de datos de Medina S.A... Cualquier intromisi&oacute;n, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en el presente har&aacute;n pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, as&iacute; como lo har&aacute; responsable de indemnizar los da&ntilde;os ocasionados.</p>

                <p>Disponibilidad / Precio de productos: La informaci&oacute;n sobre productos y precios est&aacute; sujeta a cambios sin previo aviso. Todos los precios expresados en el Sitio incluyen IVA, salvo que se indique lo contrario. Todos los precios en el Sitio est&aacute;n expresados en pesos argentinos, moneda de curso legal de la Rep&uacute;blica Argentina. No se permite la modalidad de cambio de producto por el mismo modelo y mismo talle, salvo que el cambio se deba a un defecto del producto. Antes de comprar, el Usuario deber&aacute; tener en cuenta que los productos seleccionados pueden no encontrarse disponibles. Toda compra se encuentra sujeta a disponibilidad. El Sitio solamente opera v&iacute;a internet. Por este motivo, puede ocurrir que, por m&aacute;s que sea posible ordenar la compra de un Producto en el Sitio, no haya existencias de &eacute;ste, por razones imputables a las firmas que proveen los productos al Sitio. Del mismo modo, el precio de los Productos que ofrecemos en el Sitio, puede no coincidir con el de los distintos locales o proveedores que nos abastecen. Validez de las promociones: En el caso de que se realicen ofertas y promociones de Productos, &eacute;stas tendr&aacute;n validez para las compras efectuadas desde la fecha de comienzo de las mismas, hasta la de finalizaci&oacute;n de la oferta seg&uacute;n lo expuesto en el Sitio. Los t&eacute;rminos y condiciones de las mismas ser&aacute;n comunicados en el Sitio, y estar&aacute;n siempre sujetas a la existencia en stock de los Productos ofrecidos.</p>

                <h3><strong>Responsabilidad</strong></h3>

                <p>El Usuario es responsable de toda afirmaci&oacute;n y/o expresi&oacute;n y/o acto celebrado con su nombre de usuario y contrase&ntilde;a. El Sitio se reserva el derecho, en cualquier momento y sin necesidad de dar notificaci&oacute;n previa, de retirar cualquier env&iacute;o o dar por concluido su calidad de miembro del Sitio por violaci&oacute;n de los T&eacute;rminos y Condiciones aqu&iacute; descriptos. En caso de que la informaci&oacute;n o los datos suministrados por el usuario no sean verdaderos, este ser&aacute; responsable por los da&ntilde;os que este hecho pudiera ocasionar.</p>

                <p>El Usuario acepta y reconoce que el sistema puede no siempre estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otro motivo ajeno al Sitio, motivo por el cual no podr&aacute; imput&aacute;rsele responsabilidad alguna.</p>

                <h3><strong>Modificaciones a los T&eacute;rminos y Condiciones</strong></h3>

                <p>El Sitio se reserva expresamente los siguientes derechos: (i) A modificar o eliminar, en forma unilateral, parcial o totalmente, tanto la disposiciones de los elementos que componen el Sitio, como su configuraci&oacute;n general o particular, los servicios o contenidos o sus condiciones de acceso y utilizaci&oacute;n; (ii) A denegar o retirar el acceso a este Sitio, sus servicios y contenidos, en cualquier momento y sin aviso previo, a aquellos visitantes que incumplan los T&eacute;rminos y Condiciones, (iii) A poner t&eacute;rmino, suspender o interrumpir unilateralmente, en cualquier momento y sin aviso previo, la prestaci&oacute;n del servicio del Sitio, (iv) A modificar los t&eacute;rminos de los T&eacute;rminos y Condiciones en cualquier momento. Los T&eacute;rminos y Condiciones ser&aacute;n interpretados y ejecutados de acuerdo a las leyes de la Rep&uacute;blica de Argentina. El Usuario se somete incondicionalmente a la jurisdicci&oacute;n de los tribunales de la Ciudad Aut&oacute;noma de Buenos Aires para la resoluci&oacute;n de cualquier duda, dificultad o controversia relacionada con todo o parte de los T&eacute;rminos y Condiciones.</p>

                <p>El Usuario indemnizar&aacute; y mantendr&aacute; indemne a   Medina S.A., sus filiales, empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio o por su incumplimiento los T&eacute;rminos y Condiciones Generales y dem&aacute;s Pol&iacute;ticas que se entienden incorporadas al presente o por la violaci&oacute;n de cualesquiera leyes o derechos de terceros, incluyendo los honorarios de abogados en una cantidad razonable.</p>

                <p>Se fija como domicilio de Medina S.A. la Av. Cuba 5500, Corrientes Capital, C&oacute;digo Postal 3400, Rep&uacute;blica Argentina. Si tienes alguna duda sobre los T&eacute;rminos y Condiciones Generales o dem&aacute;s pol&iacute;ticas y principios que rigen Medina S.A. consultar nuestra p&aacute;gina www.lenceriarm.com.</p>
            </div>

        </div>
 